services:
  configserver:
   image: configserverimage
   build: ./configserver
   restart: always
   container_name: congfigserver
   ports:
    - 8001:8001

  eureka:
   image: localhost/eureka
   build: ./eureka
   container_name: eurekaserver
   ports:
    - 8888:8888
   depends_on:
    - configserver
   environment:
    - SPRING_PROFILES_ACTIVE=docker

  gateway:
   image: "localhost/gateway"
   build: ./gatewayservice
   ports:
     - "8090:8090"
   networks:
     - common
   environment:
     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
   depends_on:
     - eureka

  customer:
    image: "localhost/customerservice"
    container_name: "customerservice"
    build : ./customerservice
    ports:
      - 8080:8080
    networks:
      - common
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
    depends_on:
      - eureka
      - mysql
  product:
    image: "localhost/productservice"
    container_name: "productservice"
    build: ./productservice
    ports:
      - "8081:8081"
    networks:
      - common
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8888/eureka/
    depends_on:
      - eureka
      - postgresql
  mysql:
   image: docker.io/library/mysql:latest
   environment:
     MYSQL_ROOT_PASSWORD: test
     MYSQL_DATABASE: customer_db
     MYSQL_USER: my_user
     MYSQL_PASSWORD: test
   ports:
     - "3306:3306"
   volumes:
     - mysql_data:/var/lib/mysql
  postgresql:
   image: docker.io/library/postgres:latest
   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: test
   volumes:
     - postgres_data:/var/lib/postgresql/data
   ports:
     - "5432:5432"

volumes:
  mysql_data:
  postgres_data:

networks:
  common:
    driver: bridge