spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/etiya-pair-3/EtiyaPairworkMicroserviceConfiguration.git
          default-label: main

server:
  port: 8001
