spring:
    config:
        import: "optional:configserver:"
    application:
        name: cartservice
    cloud:
        config:
            uri: http://localhost:8001
            profile: local
            label: main
